// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badge: typeof import('./components/Badge.vue')['default']
    Banner: typeof import('./components/banner.vue')['default']
    ButtonStarted: typeof import('./components/Home/ButtonStarted.vue')['default']
    Contributors: typeof import('./components/Contributors.vue')['default']
    FeaturesList: typeof import('./components/FeaturesList.vue')['default']
    HeroBanner: typeof import('./components/Home/HeroBanner.vue')['default']
    HomeHeader: typeof import('./components/Home/HomeHeader.vue')['default']
    HomePage: typeof import('./components/Home/HomePage.vue')['default']
    'HomePage old': typeof import('./components/HomePage old.vue')['default']
    HomeSection2: typeof import('./components/Home/HomeSection2.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    old: typeof import('./components/HomePage old.vue')['default']
    VPFeatures: typeof import('./components/VPFeatures.vue')['default']
  }
}
