/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badge: typeof import('./components/Badge.vue')['default']
    Contributors: typeof import('./components/Contributors.vue')['default']
    FeaturesList: typeof import('./components/FeaturesList.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    TeamMembers: typeof import('./components/TeamMembers.vue')['default']
    VPFeatures: typeof import('./components/VPFeatures.vue')['default']
    VPTeamMembers: typeof import('./components/VPTeamMembers.vue')['default']
    VPTeamMembersItem: typeof import('./components/VPTeamMembersItem.vue')['default']
  }
}
